#!/usr/bin/env bash

set -euo pipefail

export PGPORT=5432
export PGPASSWORD="${DB_ADMIN_PASSWORD}"

psql --no-psqlrc --set=ON_ERROR_STOP=on --username="${DB_ADMIN_USER}" --dbname="${DB_NAME}" <<SQL
SELECT format('CREATE ROLE %I LOGIN', '${DB_OWNER_USER}')
WHERE NOT EXISTS (
  SELECT FROM pg_catalog.pg_roles WHERE rolname = '${DB_OWNER_USER}'
)
\gexec

SELECT format('CREATE ROLE %I LOGIN', '${DB_APPLICATION_USER}')
WHERE NOT EXISTS (
  SELECT FROM pg_catalog.pg_roles WHERE rolname = '${DB_APPLICATION_USER}'
)
\gexec

ALTER ROLE "${DB_OWNER_USER}" WITH LOGIN PASSWORD '${DB_OWNER_PASSWORD}';
ALTER ROLE "${DB_APPLICATION_USER}" WITH LOGIN PASSWORD '${DB_APPLICATION_PASSWORD}';

GRANT CONNECT ON DATABASE "${DB_NAME}" TO "${DB_OWNER_USER}";
GRANT CONNECT ON DATABASE "${DB_NAME}" TO "${DB_APPLICATION_USER}";
GRANT USAGE, CREATE ON SCHEMA public TO "${DB_OWNER_USER}";
GRANT USAGE ON SCHEMA public TO "${DB_APPLICATION_USER}";
REVOKE CREATE ON SCHEMA public FROM "${DB_APPLICATION_USER}";

GRANT "${DB_OWNER_USER}" TO "${DB_ADMIN_USER}";
SET ROLE "${DB_OWNER_USER}";

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO "${DB_APPLICATION_USER}";
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO "${DB_APPLICATION_USER}";
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO "${DB_APPLICATION_USER}";

ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "${DB_APPLICATION_USER}";
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO "${DB_APPLICATION_USER}";
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT EXECUTE ON FUNCTIONS TO "${DB_APPLICATION_USER}";

RESET ROLE;
SQL

if [[ "${ENABLE_CFT_READER_ACCESS}" == "true" ]]; then
  psql --no-psqlrc --set=ON_ERROR_STOP=on --username="${DB_ADMIN_USER}" --dbname="${DB_NAME}" <<SQL
GRANT USAGE ON SCHEMA public TO "${CFT_DB_ACCESS_READER_ROLE}";

SET ROLE "${DB_OWNER_USER}";
GRANT SELECT ON ALL TABLES IN SCHEMA public TO "${CFT_DB_ACCESS_READER_ROLE}";
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT ON TABLES TO "${CFT_DB_ACCESS_READER_ROLE}";
RESET ROLE;
SQL
fi
